---
- name: Assert VAULT_ROOT_TOKEN is set
  ansible.builtin.assert:
    that: lookup('env', 'VAULT_ROOT_TOKEN') != ''
    fail_msg: "VAULT_ROOT_TOKEN env var must be set"

- name: Check for existing intermediate issuers
  ansible.builtin.command: vault list -format=json {{ vault_pki_int_path }}/issuers
  environment:
    VAULT_ADDR: "{{ vault_pki_addr }}"
    VAULT_TOKEN: "{{ lookup('env', 'VAULT_ROOT_TOKEN') }}"
    VAULT_SKIP_VERIFY: "{{ vault_pki_tls_skip_verify | lower }}"
  register: vault_pki_issuers
  changed_when: false
  failed_when: vault_pki_issuers.rc not in [0, 2]

- name: Generate intermediate CA and import signed certificate
  ansible.builtin.include_tasks: _generate_sign_import.yml
  when: vault_pki_issuers.rc == 2
