---
- name: Install Vault
  ansible.builtin.import_tasks: install.yml

- name: Configure Vault
  ansible.builtin.import_tasks: configure.yml

- name: Enable and start Vault service
  ansible.builtin.import_tasks: service.yml
